---
title: "Census Data"
author: "Annika Kufrovich"
date: "January 17, 2019"
output: html_document
---


## Notes

* Quick note: this course, like the parallel programming one, does not have a visual of the person talking to you 
* Overview of Census data 
* `geography` paramater in tidycenus defines level of aggregration, this could be by state, county, or tract and many others, here's a breakdown <https://walkerke.github.io/tidycensus/articles/basic-usage.html#geography-in-tidycensus> 
    + There are optional `state` and `county` subsetting aruments so that you aren't returned aggregate date for the whole US 
    + you can also specify whether your data comes in long or wide format with `output` 
* You can look for census variables here<https://censusreporter.org/> or by using the `loadvariables` function to download and browe census variables from the census website. You can then use the tidyverse package to narrow your search 
* Review of ggplot2 
* Looking at how you can calculate percentaes by hand for dfferent areas, pretty basic 
* Review of tidyverse 
* The practice is at least mosty, if not entirely, the code shown in the video before. Also a lot on how the census works which is fine for someone new to it and/or statistics, but i a bit basic for me 
* Working with MOEs in tidycensus 
    + Basically they're 90% confidence interval values 
    + tidycensus has functions like `moe_sum()` and `moe_product()` for calculating combined moe's 
    + Goes over visualizing moe's 
* Census Geography and tigris basics 
    + You can retrieve shape files, as sp objects, using tigris functions 
* Customizing tigris functions 
    + Cartographic boundary shape files represent the US coastline more acurately, you can et these by etting the `cb` arument equal to true 
    + By calling `options(tigris_class = "sf"), you can get f rather than sp objects 
    + Can load objects faster with `options(tigris_use_cache = TRUE)` 
    + If doing analyses over time, may want to specify year since boundaries of counties, but more often tracts, can change over time 
* `rbind_tigris()` combines like attributed patial data sets 
* Review of joining data from a data frame 
* Review of ggplot2 plotting

## Practice/Application

```{r, include=FALSE}
library(tidycensus)
library(tidyverse)
library(tigris)
library(ggplot2)


#census_api_key("864d0c376476571c0dee5dff3422e4a3b75ab093", install = TRUE)
```



## Goals for tomorrow 



