---
title: "Intermediate R Notes"
author: "Annika Kufrovich"
date: "January 5, 2019"
output: html_document
---

##Notes

* Starts with review of relational Operators, I know these: ==, !=, <, >, <=, and >= 
    + One thing is that these operators work for strings in alphebetical order 
* Review of logical operators, know these as well, &, |, and ! 
* && and || only evaluate the first element of a vector 
* Review of if and else statements and while/for loops 
* Skipped functions chapter because larger course on functions 
* Apply family 
    + lapply can apply a function (such as class) to all the components of something (like a list or vector) and always returns a list
    + sapply does what lapply does but automatically puts the output into a vector, array, or matrix, however, sapply returns a list if outcome vectors are not the same length 
    + vapply is like lapply and sapply but you have to specify the form of the output 
* reviewing general mathematical functions, know these
* regular expressions
    + grepl looks for a pattern (indicated by a regex) in something, returns logical output
    + grep is similar to grepl but instead of returning logical output, outputs instances where function came out true
    + sub adds onto grepl by adding a replacement argument for each iteration
    + gsub is like sub but allows replacement past the first instance in each iteration, ie replaces both a's with o's in impala (now impolo), whereas gsub would only replace the first a, makin the new string "impola"
    + `".*"` in a regular expressions takes place of characters that could be unmatched between two things you're looking for in a pattern
    + Ex. in `"@.*\\.edu$"`, characters between @ and .edu are ignored/mathced by `".*"` so that your pattern earches for valid .edu email addresses
    + regular expressions can get very complex, will need practice
    + `"\\s"` indicates a space in regex as it "escapes" the normal s character and makes it a metacharacter
*Times and Dates, review of basic date/time transformations, I've used lubridate which is more advanced


## Practice

Decided not to practice material from intermediate R course because most was review, will likely get regex practice in goals tomorrow or can revisit in Intermediate R Practice course

## Goals for tomorrow and the day after
* Finish data camp functions course
* Practice by trying to figure out a function that checks if a row from the new voter file matches one in older voter file (will do this with smaller county level voter file)
  + will add a column with TRUE outcomes for matched voters and FALSE for unmatched voters for verification
* If this works, continue to create lon/lat columns that take geocoded lon/lat of old matched voters and puts those values in the new lon/lat columns of new matched voters
    + This should leave only new voters and moved voters without lon/lat values (ie all original falses should not have lon/lat)
*Note: final function requires the use of 3 datasets: old ungeocoded voter file, new ungeocoded file voter file, and old geocoded voter file. If I take the old geocoded dataset, I should simply have to use dplyr to remove the lon/lat columns to create the old ungeocoded dataset. While having all 3 datasets downloaded is certainly possible, this or finding a way to ignore the lon/lat columns in my initial comparison 