---
title: "ISP Final Project"
author: "Annika Kufrovich"
date: "January 18, 2019"
output: html_document
---


```{r, include=FALSE}
library(tidycensus)
library(tigris)
library(ggplot2)
library(ggmap)
library(dplyr)
library(sf)
library(spatstat)
```


## Function quick look 

Test Dataframes

```{r, warning=FALSE, message=FALSE}
test1b <- data.frame(numbers = 1:8, letters = c("a", "b", "c", "d", "a", "b", "c", "d"))
test4b <- data.frame(numbers = 1:8, letters = c("a", "b", "c", "d", "a", "b", "c", "e"), lon = c(12, 31, 64, 38, 89, 73, 91, 21))
```

Function

```{r, warning=FALSE, message=FALSE}
matching_dfs_addcol <- function(newdf, olddf) {
  matching <- semi_join(olddf, newdf)
  matching_col <- matching %>%
    mutate(matched = TRUE)
  not_matching <- anti_join(newdf, olddf)
  not_matching_col <- not_matching %>%
    mutate(matched = FALSE)
  combined_df <- full_join(matching_col, not_matching_col)
  combined_df
}

new_func_test <- matching_dfs_addcol(test1b, test4b)
new_func_test
```



## Geocoding 

```{r}
new_lib <- read.delim("C:/Users/TeenieTiny/Desktop/2nd Year/Data/Voter_Registration_20181113/20181113_VoterDetail/LIB_20181113.txt", header=FALSE)



#this didn't work with mutate_geocode, alternatives with commas didn't help
#new_lib_addres <- new_lib %>% 
#  mutate(address = paste(V8, V10, V12, sep = " "))


#thought this would fix it, it didn't, alternatives with commas didn't help
#new_lib_addres <- new_lib %>% 
#  mutate(address = paste(V8, V10, V12, sep = ", "), stringsAsFactors = FALSE)


new_lib_addres <- new_lib %>% 
  mutate(address = paste(V8, V10, "FL", sep = ", "))
```



```{r, warning=FALSE, message=FALSE}
#geocoding first 1000 obs
nl_p1 <- new_lib_addres %>% 
  slice(1:1000)

nl_geocode_p1 <- nl_p1 %>%
  mutate_geocode(address, source = "dsk")


#2nd 1000 obs
nl_p2 <- new_lib_addres %>%
  slice(1001:2000)

nl_geocode_p2 <- nl_p2 %>%
  mutate_geocode(address, source = "dsk")


#3rd 1000 obs
nl_p3 <- new_lib_addres %>%
  slice(2001:3000)

nl_geocode_p3 <- nl_p3 %>%
  mutate_geocode(address, source = "dsk")


#4th 1000 obs
nl_p4 <- new_lib_addres %>%
  slice(3001:4000)

nl_geocode_p4 <- nl_p4 %>%
  mutate_geocode(address, source = "dsk")


#
nl_p5 <- new_lib_addres %>%
  slice(4001:4626)

nl_geocode_p5 <- nl_p5 %>%
  mutate_geocode(address, source = "dsk")



#I should have made a function, making this one and will test if it works later
geocoding <- function(df, address_col, seq) {
  sliced <- df %>% 
    slice(seq)
  geocoded <- sliced %>% 
    mutate_geocode(address_col, source = "dsk")
}


#joining all geocoded datasets
nl_join <- full_join(nl_geocode_p5, full_join(nl_geocode_p4, full_join(nl_geocode_p3, full_join(nl_geocode_p1, nl_geocode_p2))))

```


## Getting shape of liberty county

```{r, warning=FALSE, message=FALSE}
#retrieving sp object in case sf object doesn't behave
options(tigris_class = "sp")
fl_counties <- counties(state = "FL")
plot(fl_counties)


#retrieving sf object because it will probably be easier to isolate liberty county this way
options(tigris_class = "sf")
fl_counties2 <- counties(state = "FL")
plot(fl_counties2$geometry)


#isolating liberty county
liberty <- fl_counties2 %>% 
  filter(NAME == "Liberty")
plot(liberty$geometry)
```
 
 
Now that we have the geometry, let's check if things match up

```{r}
liberty$geometry

min(nl_join$lon, na.rm = TRUE)
max(nl_join$lon, na.rm = TRUE)
max(nl_join$lat, na.rm = TRUE)
min(nl_join$lat, na.rm = TRUE)
```

the mins and max's don't match, before I try to narrow this down, lets see what happens if I try to put my data and geometry in to a ppp object 


```{r, warning=FALSE, message=FALSE}
#making my window 
libwin <- owin(xy = liberty$geometry)
plot(libwin)
summary(libwin)
#this didn't come out the way I expected it to, just made a square ranging from 0 to 1 on each axis
#may come back to this




#transforming lat/lon coordinates to x/y coordinates and reducing to 0-1 scale
nl_jxy <- nl_join %>% 
  mutate(y = lon, x = lat)

nl_min <- nl_jxy %>% 
  select(x, y, V29, V24)

minx <- min(nl_min$x, na.rm = TRUE)
maxx <- max(nl_min$x, na.rm = TRUE)

nl_min$x <- (nl_min$x - minx)/(maxx - minx)

miny <- min(nl_min$y, na.rm = TRUE)
maxy <- max(nl_min$y, na.rm = TRUE)

nl_min$y <- (nl_min$y - miny)/(maxy - miny)



#Making unmarked ppp object

libppp <- ppp(nl_min$x, nl_min$y, window = libwin)

#ppp object marked by voter status (Active vs Inactive)
libppp_act <- ppp(nl_min$x, nl_min$y, window = libwin, marks = nl_min$V29)



#Making party variable
#may change this to case_when later
summary(nl_min$V24)

nl_min <- nl_min %>%
  mutate(party = ifelse(V24 == "DEM", "Democrat", 
                        ifelse(V24 == "REP", "Republican", "NPA/Other")))

#ppp marked by party
libppp_party <- ppp(nl_min$x, nl_min$y, window = libwin, marks = nl_min$party)
```



## Tests and Plots

