---
title: "Spatial Analysis with sf and raster"
author: "Annika Kufrovich"
date: "January 13, 2019"
output: html_document
---

## Notes
* Read in vector data with the function `st_read()` from the sf package 
    + simplifies things by just taking a filepath and figurin out the proper fomat from the . suffix 
* Read in raster data with the the either the `raster()` or `brick` function from the raster package 
    + `raster()` function reads in single-band rasters 
    + `brick()` function reads in multi-band rasters 
    + Single-band rasters have a single set of values for each grid cell, ex elevation or land use rasters 
    + Multi-band rasters may have multiple values for each grid cell, ex satellite images or aerial photos which woul be pslit up by bands of light 
* To write data use `st_write()` for vector data and `writeRaster()` for raster data
* sf package stores spatial objects as dataframes which allow the use of dplyr to work with them 
    + These dataframes include metadata like CRS and geometry is stored in a list column 
    + makes sens to have a list column becaue each polygon can have varying amounts of information on its geometry 
    + you can ue the `is.list()` function to figure out which columns are lists 
    + use the `st_geometry()` function to pull out the geometry of a spatial object before plotting 
* Raster objects will be tored with the class rasterLayer or rasterBrick, for single- and multi-band rasters respectively 
    + You can extract metadata from these with the functions `extent()` for (variable ranges), `crs()`, `ncell()`, and `nlayerS()` 
    + Check if raster values are in memory with `inMemory()` 
    + Use `getValues()` function to et values if they are not in memory, will become a vector for a single-layer raster and a matrix for a multi-layer raster 
    + `plotRGB()` can combine multi-layer rasters based on Red, Green, and Blue light to create a single, true color image 
* Review of CRS 
    + Use `st_crs()` for vectors and `crs()` for rasters 
* `st_simplify()` reduces the size of large shape files without reducing vertices in such a way that the shape is significantly different, makes analysis go faster. You can check ize with `objectsize()`
* Converting between sp andf sf 
    + After reading in your file with st_read, convert to sp object with `as(mysfobject, class = "Spatial")`
    + for the reverse use `st_as_sf(myspobject)` 
* COnverting to and from coordinates 
    + After reading in dataframe with lon and lat, use `st_as_sf(mydf, coords = c("lon", "lat"))`, you'll aso need to add a crs argument to specify the coordinate system 
    + `st_write(myspatialfile, "newfilename.csv", layer_options = "GEOMETRY=AS_XY")` to pass coordinates into your csv file 
* Manipulating raster layers 
    + to simplify large rasters you can use the `aggregate()` function from the raster package with the argument `fact` for the factor you want to reduce resolution by and `fun` to specify how you want to aggregate 
    + This is another way to reduce file size 
    + `reclassify()` function, takes in a matrix for the argument `rcl` to change a single or set of values to a new value, have multiple rows for multiple rules 
* Buffers and Centroids 
    + General rule: Layers should use a projected CRS, with the crs being the same between layers if there are multiple
    + For sf, buffer function is `st_buffer()` with the first argument being the buffer radius using the units of your CRS 
    + You can compute centroids with `st_centroid()` which is generally run with one argument (data argument) 
* Bounding Boxes, dissolve features and create a convex hull 
    + Regions can be defined as rectangles or a tighter polygon with a convex hull 
    + You can compute bounding box coordinates with the function `st_bbox()` 
    + you can intead create a bouning box with `st_make_grid` which normally makes a large grid, however you can specify the argument `n = 1` to make a single polygon bounding box 
    + `st_union()` disolves features, for polygons the function takes a et of polygon and dissolves them into a single feature, for points it will cluster individual points int a multipoint geometry 
    + The latter is a required step for some computations like convex hull 
* Multi-layer geoprocessing and relationships 
    + A spatial join joins objects based on geography, you can do this with `st_join()`, where the first argument i the object you want as an output and the second is the object with the attributes you want added 
    + `st_intersects()` and `st_contains()` could help you determine what roads intersect or are contained in our polygon(s) of interest, must subset after each function 
    + `st_intersections()` is like `st_intersect()` but cuts off at the boundaries of the polygon 
    + `st_distance()` can help us find the distance between features, such as a road and a centroid, you just input  your layers to the function and it will include the distance from each feature in one layer to each feature in another layer as a matrix 
* Geoprocessing with rasters 
    + Raster package hasn't been updated to use sf objects, must convert with `as()` function 
    + `mask()` function takes raster object and a mask object and will only keep the values sithin the mask object, setting all other values to NA 
    + `extract()` can take points or polygons, with polygons able to take a function to aggregate inthe `fun` argument 
    + `overlay()` takes raster layers and does raster math 
* No Day 2 notes, all review and application

## Practice/Application

```{r, include=FALSE}
library(sf)
library(raster)
library(ggplot2)
library(tmap)
library(dplyr)
```

More Ideas:
Add my geocoded voters to an sf object 
Maybe also add precinct location data and look at distance between voters and voting location?


## Goals for Tomorrow
* Finish Spatial analysis course
* Work on geocoding function and try to decide on a way to analyze the data post-geocoding



